config/routes.rb
Rails.application.routes.draw do

  resources :wikis
  devise_for :users

  # root 'welcome#index'
  root 'users#show'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :wikis

 # def email_required?
 #   false
 # end
 #
 # def email_changed?
 #   false
 # end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # Redirect the user to login page if not authenticated
  before_action :authenticate_user!
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

def show
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authenticate_user!, :only => [:index, :new]

  def index
  end

  def about
  end

  def edit
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :set_wiki, only: [:show, :edit, :update, :destroy]

  # GET /wikis
  def index
    @wikis = Wiki.all
  end

  # GET /wikis/1
  def show
  end

  # GET /wikis/new
  def new
    @wiki = Wiki.new
  end

  # GET /wikis/1/edit
  def edit
  end

  # POST /wikis
  def create
    @wiki = current_user.wikis.new(wiki_params)

    if @wiki.save
      redirect_to @wiki, notice: 'Wiki was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /wikis/1
  def update
    if @wiki.update(wiki_params)
      redirect_to @wiki, notice: 'Wiki was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /wikis/1
  def destroy
    @wiki.destroy
    redirect_to wikis_url, notice: 'Wiki was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki
      @wiki = Wiki.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def wiki_params
      params.require(:wiki).permit(:title, :body, :private)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tab">
      <div class="pull-right user-info">
         <% if user_signed_in? %>
           Signed in as: <strong><%= current_user.email %></strong> |
           <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
         <% else %>
           <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
           <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
         <% end %>
      </div>
   </ul>
   <div>
   <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="media">
      <br />
      <div class="media-body">
        <h2 class="media-heading"><%= current_user.username %></h2>
        <small>
            <%= pluralize(current_user.wikis.count, 'wikis') %>
        </small>
      </div>
    </div>
  </div>
</div>

<h2>Wikis</h2>
<%= render current_user.wikis %>

app/views/welcome/about.html.erb
 <h1>About Blocipedia</h1>
 <p>Created by: Paul Collins</p>

app/views/welcome/index.html.erb
<h1>Welcome to Blocipedia</h1>
<p>This is the home page for Blocipedia</p>

<% if user_signed_in? %>
  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
<% end %>

app/views/wikis/_form.html.erb
<%= form_for(@wiki) do |f| %>
  <% if @wiki.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wiki.errors.count, "error") %> prohibited this wiki from being saved:</h2>

      <ul>
      <% @wiki.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter Wiki Title"%>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, rows: 10, class: "form-control", placeholder: "Enter Wiki Body Text" %>
  </div>
  <div class="field">
    <%= f.label :private %><br>
    <%= f.check_box :private %>
  </div>
  <div class="actions">
    <%= f.submit "Save Wiki", class: "btn btn-success"%>
  </div>
<% end %>

app/views/wikis/_wiki.html.erb
<%= content_tag :div, class: 'media', id: "wiki-#{wiki.id}" do %>
   <div class="media-body">
     <small>
         <%= link_to "Delete", [wiki], method: :delete, remote: true %>
     </small>
     <p><%= wiki.body %></p>
   </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Editing Wiki</h1>

<%= render 'form' %>

<%= link_to 'Show', @wiki %> |
<%= link_to 'Back', wikis_path %>

app/views/wikis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wikis</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Private</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wikis.each do |wiki| %>
      <tr>
        <td><%= wiki.title %></td>
        <td><%= wiki.body %></td>
        <td><%= wiki.private %></td>
        <td><%= wiki.user %></td>
        <td><%= link_to 'Show', wiki %></td>
        <td><%= link_to 'Edit', edit_wiki_path(wiki) %></td>
        <td><%= link_to 'Delete', wiki, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wiki', new_wiki_path %>

app/views/wikis/new.html.erb
<h1>Enter New Wiki</h1>

<%= render 'form' %>

<%= link_to 'Back', wikis_path %>

app/views/wikis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @wiki.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @wiki.body %>
</p>

<p>
  <strong>Private:</strong>
  <%= @wiki.private %>
</p>

<p>
  <strong>User:</strong>
  <%= @wiki.user.email %>
</p>

<%= link_to 'Edit', edit_wiki_path(@wiki) %> |
<%= link_to 'Back', wikis_path %>